# Generated by Django 3.1.1 on 2021-02-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_auto_20210128_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
