# Generated by Django 3.1.1 on 2021-03-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_auto_20210218_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100, verbose_name='Location Name')),
            ],
            options={
                'verbose_name_plural': 'Hotel Location',
            },
        ),
    ]
