# Generated by Django 3.1.1 on 2021-03-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location_id',
            field=models.ManyToManyField(to='frontend.Location', verbose_name='Location'),
        ),
    ]
