# Generated by Django 3.1.1 on 2021-03-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_hotel_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four'), (5, 'five'), ('', 'Choose Rating')], default='', max_length=15),
        ),
    ]
