# Generated by Django 3.1.1 on 2021-03-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='location_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Location Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(choices=[('one', '1'), ('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('', 'Choose Rating')], default='', max_length=15),
        ),
    ]
